Vagrant.configure("2") do |config|
    config.vm.box = "alpine/alpine64"
    config.vm.network "private_network", ip: "192.168.100.13"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
    end
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
